# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e55d8ea291b954c03ecb23f69953775c922df83bc3d49f21826031acfbeed6d760994716cde1799653d0061e69a1f8838c7e332ee79d232edb1eb48bb16bd1

test:
  secret_key_base: da8f21501fbaa46ddf9fdf90f69c5f964d180865b021bdc20c6a8fac812d650114881db79e127a2c6bc87be35a861f7ebb82efde35d1afb4770fbcdc294ac44f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
