require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DistancesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Distance. As you add validations to Distance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DistancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all distances as @distances" do
      distance = Distance.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:distances)).to eq([distance])
    end
  end

  describe "GET #show" do
    it "assigns the requested distance as @distance" do
      distance = Distance.create! valid_attributes
      get :show, params: {id: distance.to_param}, session: valid_session
      expect(assigns(:distance)).to eq(distance)
    end
  end

  describe "GET #new" do
    it "assigns a new distance as @distance" do
      get :new, params: {}, session: valid_session
      expect(assigns(:distance)).to be_a_new(Distance)
    end
  end

  describe "GET #edit" do
    it "assigns the requested distance as @distance" do
      distance = Distance.create! valid_attributes
      get :edit, params: {id: distance.to_param}, session: valid_session
      expect(assigns(:distance)).to eq(distance)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Distance" do
        expect {
          post :create, params: {distance: valid_attributes}, session: valid_session
        }.to change(Distance, :count).by(1)
      end

      it "assigns a newly created distance as @distance" do
        post :create, params: {distance: valid_attributes}, session: valid_session
        expect(assigns(:distance)).to be_a(Distance)
        expect(assigns(:distance)).to be_persisted
      end

      it "redirects to the created distance" do
        post :create, params: {distance: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Distance.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved distance as @distance" do
        post :create, params: {distance: invalid_attributes}, session: valid_session
        expect(assigns(:distance)).to be_a_new(Distance)
      end

      it "re-renders the 'new' template" do
        post :create, params: {distance: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested distance" do
        distance = Distance.create! valid_attributes
        put :update, params: {id: distance.to_param, distance: new_attributes}, session: valid_session
        distance.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested distance as @distance" do
        distance = Distance.create! valid_attributes
        put :update, params: {id: distance.to_param, distance: valid_attributes}, session: valid_session
        expect(assigns(:distance)).to eq(distance)
      end

      it "redirects to the distance" do
        distance = Distance.create! valid_attributes
        put :update, params: {id: distance.to_param, distance: valid_attributes}, session: valid_session
        expect(response).to redirect_to(distance)
      end
    end

    context "with invalid params" do
      it "assigns the distance as @distance" do
        distance = Distance.create! valid_attributes
        put :update, params: {id: distance.to_param, distance: invalid_attributes}, session: valid_session
        expect(assigns(:distance)).to eq(distance)
      end

      it "re-renders the 'edit' template" do
        distance = Distance.create! valid_attributes
        put :update, params: {id: distance.to_param, distance: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested distance" do
      distance = Distance.create! valid_attributes
      expect {
        delete :destroy, params: {id: distance.to_param}, session: valid_session
      }.to change(Distance, :count).by(-1)
    end

    it "redirects to the distances list" do
      distance = Distance.create! valid_attributes
      delete :destroy, params: {id: distance.to_param}, session: valid_session
      expect(response).to redirect_to(distances_url)
    end
  end

end
